"""
이 프로젝트의 모든 설정 상수를 중앙에서 관리합니다.
"""

# --- 일반 설정 ---
COL_ACCESS_TIME = "접속일시"
COL_EMPLOYEE_ID = "교직원ID"
EXCEL_EXTENSIONS = (".xlsx", ".xls")
SHEET_NAME_MAX_CHARS = 31

# --- 로그인 검사기 (login_checker.py) ---
LOGIN_LOG_FILE_PREFIX = "사용자접속내역_Login내역_"
LOGIN_CHECK_REPORT_BASE = "[붙임2] 코러스 사용자 접근 기록"
LOGIN_REPORT_IP_SWITCH_SUFFIX = "60분IP"
LOGIN_REPORT_OFF_HOURS_SUFFIX = "업무시간외"
LOGIN_REPORT_HOLIDAY_SUFFIX = "휴일"
COL_IP = "IP"
LOGIN_IP_SWITCH_WINDOW_HOURS = 1
LOGIN_IP_SWITCH_MIN_IPS = 3
LOGIN_OFF_HOURS_START = 23
LOGIN_OFF_HOURS_END = 7

# --- 개인정보 파일 접근 검사기 (personal_file_checker.py) ---
PERSONAL_INFO_ACCESS_LOG_PREFIX = "개인정보 접속기록 조회_"
PERSONAL_INFO_REPORT_BASE = "[붙임3] 개인정보 접속 기록"
MERGED_PERSONAL_INFO_ACCESS_FILENAME_TEMPLATE = "[붙임3] 개인정보 접속 기록_{}.xlsx"
PERSONAL_INFO_ACCESS_MASTER_SUFFIX = "인사마스터"
PERSONAL_INFO_ACCESS_HIGH_VOLUME_VIEWS_SUFFIX = "1000건이상조회"
PERSONAL_INFO_ACCESS_HIGH_VOLUME_SAVES_SUFFIX = "100건이상저장"
COL_PROGRAM_NAME = "프로그램명"
COL_DETAIL_CONTENT = "상세내용"
COL_JOB_PERFORMANCE = "수행업무"
COL_EMPLOYEE_NAME = "성명"
VIEW_THRESHOLD = 1000
SAVE_THRESHOLD = 100

# --- 다운로드 사유 검사기 (download_reason_checker.py) ---
PERSONAL_INFO_DOWNLOAD_REASON_PREFIX = "개인정보 다운로드 사유 조회_"
DOWNLOAD_REASON_REPORT_BASE = "[붙임4] 개인정보 다운로드 사유"
DOWNLOAD_REASON_INVALID_REASON_SUFFIX = "사유이상"
DOWNLOAD_REASON_HIGH_DOWNLOAD_COUNT_SUFFIX = "100건 초과"
DOWNLOAD_REASON_HIGH_FREQUENCY_SUFFIX = "1시간20건초과"
DOWNLOAD_REASON_OFF_HOURS_SUFFIX = "업무시간외"
COL_DOWNLOAD_REASON = "다운로드사유"
COL_DOWNLOAD_COUNT = "다운로드데이터수(건)"
DOWNLOAD_COUNT_THRESHOLD = 100
DOWNLOAD_FREQUENCY_THRESHOLD = 20
DOWNLOAD_OFF_HOURS_START = 23
DOWNLOAD_OFF_HOURS_END = 8
